from .base import build_state

# Verified against louisiana.gov Agency Directory + individual agency
# sites, Jul 2026.
RAW = {
    "01": ("Coastal Protection and Restoration Authority", "site:coastal.la.gov filetype:pdf"),
    "02": ("Department of Agriculture and Forestry", "site:ldaf.la.gov filetype:pdf"),
    "03": ("Department of Children and Family Services", "site:dcfs.louisiana.gov filetype:pdf"),
    "04": ("Department of Corrections", "site:doc.louisiana.gov filetype:pdf"),
    "05": ("Department of Culture, Recreation, and Tourism", "site:crt.state.la.us filetype:pdf"),
    "06": ("Department of Education", "site:doe.louisiana.gov filetype:pdf"),
    "07": ("Department of Environmental Quality", "site:deq.louisiana.gov filetype:pdf"),
    "08": ("Department of Health", "site:ldh.louisiana.gov filetype:pdf"),
    "09": ("Department of Insurance", "site:ldi.la.gov filetype:pdf"),
    "10": ("Department of Justice / Attorney General", "site:ag.louisiana.gov filetype:pdf"),
    "11": ("Department of Natural Resources", "site:dnr.louisiana.gov filetype:pdf"),
    "12": ("Department of Public Safety", "site:dps.louisiana.gov filetype:pdf"),
    "13": ("Department of Revenue", "site:revenue.louisiana.gov filetype:pdf"),
    "14": ("Department of Treasury", "site:treasury.la.gov filetype:pdf"),
    "15": ("Department of Transportation and Development", "site:dotd.la.gov filetype:pdf"),
    "16": ("Department of Veterans Affairs", "site:vetaffairs.la.gov filetype:pdf"),
    "17": ("Department of Wildlife and Fisheries", "site:wlf.louisiana.gov filetype:pdf"),
    "18": ("Division of Administration", "site:doa.la.gov filetype:pdf"),
    "19": ("Governor's Office of Homeland Security and Emergency Preparedness", "site:gohsep.la.gov filetype:pdf"),
    "20": ("Louisiana's Community and Technical College System", "site:lctcs.edu filetype:pdf"),
    "21": ("Louisiana Division of Administrative Law", "site:adminlaw.la.gov filetype:pdf"),
    "22": ("Louisiana Economic Development", "site:opportunitylouisiana.com filetype:pdf"),
    "23": ("Louisiana Ethics Administration Program", "site:ethics.la.gov filetype:pdf"),
    "24": ("Louisiana Legislature", "site:legis.la.gov filetype:pdf"),
    "25": ("Louisiana State University System", "site:lsu.edu filetype:pdf"),
    "26": ("Louisiana Supreme Court", "site:lasc.org filetype:pdf"),
    "27": ("Louisiana Workforce Commission", "site:laworks.net filetype:pdf"),
    "28": ("Office of the Governor", "site:gov.louisiana.gov filetype:pdf"),
    "29": ("Office of Juvenile Justice", "site:ojj.la.gov filetype:pdf"),
    "30": ("Public Service Commission", "site:lpsc.louisiana.gov filetype:pdf"),
    "31": ("Secretary of State", "site:sos.la.gov filetype:pdf"),
    "32": ("Southern University System", "site:sus.edu filetype:pdf"),
    "33": ("State Civil Service", "site:civilservice.louisiana.gov filetype:pdf"),
    "34": ("University of Louisiana System", "site:ulsystem.edu filetype:pdf"),
    "35": ("Louisiana House of Representatives", "site:house.louisiana.gov filetype:pdf"),
    "36": ("Louisiana Senate", "site:senate.la.gov filetype:pdf"),
    "37": ("Louisiana Legislative Auditor", "site:lla.la.gov filetype:pdf"),
    "38": ("Louisiana Supreme Court E-Filing / CDX", "site:cdx.lasc.org filetype:pdf"),
    "39": ("Louisiana Board of Regents", "site:laregents.edu filetype:pdf"),
    "40": ("Board of Elementary and Secondary Education (BESE)", "site:bese.louisiana.gov filetype:pdf"),
    "41": ("Louisiana State Police", "site:lsp.org filetype:pdf"),
    "42": ("Office of Motor Vehicles (DPS ExpressLane)", "site:expresslane.dps.louisiana.gov filetype:pdf"),
    "43": ("State Fire Marshal", "site:lasfm.louisiana.gov filetype:pdf"),
    "44": ("Office of Financial Institutions", "site:ofi.la.gov filetype:pdf"),
    "45": ("Louisiana Military Department / National Guard", "site:geauxguard.la.gov filetype:pdf"),
    "46": ("Real Estate Commission", "site:lrec.gov filetype:pdf"),
    "47": ("Louisiana Checkbook (Transparency Portal)", "site:checkbook.la.gov filetype:pdf"),
    "48": ("State Government Jobs Portal", "site:jobs.la.gov filetype:pdf"),
    "49": ("State Library of Louisiana", "site:state.lib.la.us filetype:pdf"),
    "50": ("State Board of Medical Examiners", "site:lsbme.la.gov filetype:pdf"),
}

STATE = build_state("LA", "Louisiana", RAW)
